# NUMPY

CREATING ARRAY 

In [1]:
import numpy as np
arr= np.array([1,2,3])
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [2]:
zeros_array=np.zeros((2,3))
ones_array=np.ones((3,2))
print(zeros_array)
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
arr1=np.arange(0,10,2) #array from 0 to 10 with a step of 2 and last skipped

arr1


array([0, 2, 4, 6, 8])

In [9]:
arr2=np.linspace(0,1,5) 
arr2

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
arr2=np.linspace(0,10,5) 
arr2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
arr2=np.linspace(0,20,5) 
arr2

array([ 0.,  5., 10., 15., 20.])

In [12]:
random_arr=np.random.rand(2,3)
random_arr

array([[0.22725047, 0.90546548, 0.3284892 ],
       [0.1513542 , 0.17732923, 0.97110668]])

In [34]:
random_arr=np.random.rand(3,3)*9+1 #range becomes 1 to 10
random_arr

array([[1.71422371, 3.3134052 , 4.79840999],
       [9.92844678, 2.31770802, 9.39083245],
       [9.91937551, 2.74494377, 1.13973289]])

In [35]:
random_arr=np.random.rand(3,3)*10 #range may go below 1
random_arr

array([[9.85325529, 4.47692738, 2.02401819],
       [9.48053714, 5.96193551, 7.69877347],
       [1.48203082, 7.41741792, 4.69682487]])

In [20]:
random_arr=np.random.randint(1,10,(3,3)) #integer random value (random.randint(low, high=None, size=None, dtype=int))
random_arr

array([[6, 1, 2],
       [2, 8, 8],
       [9, 7, 3]])

In [29]:
random_arr=np.random.randint(low=5,size=(3,3))
print(random_arr)

[[4 3 3]
 [3 3 0]
 [4 3 1]]


In [18]:
arr=np.array([1,2,3,4,5])
print(arr[2])

3


In [21]:
arr=np.array([4,6,7,8,5,3])
print(arr[1:4])

[6 7 8]


In [22]:
arr=np.array([4,6,7,8,5,3])
print(arr[0:4])

[4 6 7 8]


In [37]:
arr3=np.random.randint(low=1,high=10,size=7)
print(arr)
print(arr[2])

[4 6 7 8 5 3]
7


In [42]:
arr3=np.random.randint(low=1,high=10,size=7)
#print(arr)
print(arr[2])
arr[3]=20
print(arr)

7
[ 4  6  7 20  5  3]


In [41]:
multi_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(multi_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(2,5)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
