In [3]:
import numpy as np 
arr1=np.array([1,4,3,5,6,7,4,2,5,6])
n_arr1=arr1[1:4]
n_arr1

array([4, 3, 5])

In [20]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
#print(arr2)
#arr2[0,1]
#arr2[0,0:2]
#arr2[0:2,0:2]
arr2[0:3,0:2] #1st dim is row and second dim is column

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [21]:
arr3=np.array([[[1,2],[3,4],[5,6]],[[7,8],[8,9],[9,10]],[[11,12],[13,14],[14,15]]])
print(arr3)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 8  9]
  [ 9 10]]

 [[11 12]
  [13 14]
  [14 15]]]


In [36]:
print(arr3[0:,1,0:2])

[[ 3  4]
 [ 8  9]
 [13 14]]


In [34]:
arr3


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 8,  9],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [14, 15]]])

In [45]:
arr4=np.array([1,2,3,4,5,6,7,8])
n_arr=arr4.copy()
arr4[0]=100
print(arr4)
print(n_arr)

[100   2   3   4   5   6   7   8]
[1 2 3 4 5 6 7 8]


In [46]:
arr4=np.array([1,2,3,4,5,6,7,8])
n_arr=arr4.copy()
arr4[0]=100
n_arr[0]=20
print(arr4)
print(n_arr)

[100   2   3   4   5   6   7   8]
[20  2  3  4  5  6  7  8]


In [47]:
arr4=np.array([1,2,3,4,5,6,7,8])
copy_arr=arr4.copy()
view_array=arr4[1:]
print(arr4)
print(copy_arr)
print(view_array)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]


copy can be also be done as 

In [52]:
arr5=np.array([5,6,7,8,8,9])
cop_array=arr5.copy()
arr_view=arr5.view()
print(cop_array)
print(arr_view)

[5 6 7 8 8 9]
[5 6 7 8 8 9]


In [54]:
arr5=np.array([5,6,7,8,8,9])
cop_array=arr5.copy()
arr_view=arr5.view()
arr5[0]=10
print(arr5)
print(cop_array)
print(arr_view)

[10  6  7  8  8  9]
[5 6 7 8 8 9]
[10  6  7  8  8  9]


In [60]:
arr6=np.array([1,2,3],dtype='float64')
print(arr6)
arr6=np.array([1,2,3],dtype='int')
print(arr6)
arr6=np.array([1,2,3],dtype='str')
print(arr6)

[1. 2. 3.]
[1 2 3]
['1' '2' '3']
