In [19]:
import numpy as np 
arra=np.array([1,24,6,4,3,67,23])
arr=np.array([[1,2,3],[4,6,7]])
print(arr.shape) #order
print(arr.ndim) #dimension
print(arr.size) #no of elements
print(arra.size)
print(arra.ndim)
print(arra.shape)
type(arr)

(2, 3)
2
6
7
1
(7,)


numpy.ndarray

In [7]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_arr=arr1.reshape((2,6))
print(reshaped_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
reshaped_arr1=arr1.reshape((3,4))
print(reshaped_arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
reshaped_arr2=arr1.reshape((2,2,-1)) #if -1 is given then automatically it takes the 3rd dimension
reshaped_arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
reshaped_arr3=arr1.reshape((-1)) #changed to 1d array(12 can also be given as the dimension)
reshaped_arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr8=np.array([[[1,2],[3,4],[5,6]],[[7,8],[8,9],[9,10]],[[11,12],[13,14],[14,15]]]) #slicing
print(arr8)
arr8[2,2,1] #(1st check height,thenrow of that block,then column)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 8  9]
  [ 9 10]]

 [[11 12]
  [13 14]
  [14 15]]]


15

In [23]:
for i in arr1:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [24]:
for i in arr:
    print(i)

[1 2 3]
[4 6 7]


In [25]:
arr=np.array([[1,2,3],[4,6,7]])
for i in np.nditer(arr): #giving all elments of array(independent of dimension)
    print(i)

1
2
3
4
6
7


In [28]:
arr2=np.array([30,60,90]) #value taken in radians 
sin_arr=np.sin(arr2)
print(sin_arr)

[-0.98803162 -0.30481062  0.89399666]


In [31]:
matrix_a=np.array([[1,2],[4,5]])
matrix_b=np.array([[6,7],[8,9]])
result=np.dot(matrix_a,matrix_b)
result

array([[22, 25],
       [64, 73]])